<?php echo $this->doctype();
$language = substr($this->plugin('translate')->getTranslator()->getLocale(), 0,2);

//$language = "ru";?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Family'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css', 'screen,print')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css', 'screen,print')
        ->prependStylesheet($this->basePath() . '/css/list.css', 'screen,print')?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/list.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>


<body>
    <div class="container-fluid">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->url('home').$language ;?>"><?php echo $this->translate('Big Family Project') ?></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="<?php echo $this->url("home/default", 
                array('language'=>$language,'controller' => 'About', 'action' => 'nil')) ?>">
                <?php echo $this->translate('Nil Shirokov') ?>
            </a></li>
        <li><a href="<?php echo $this->url("home/default", 
                array('language'=>$language,'controller' => 'About', 'action' => 'book')) ?>">The Book</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">The Project <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="tree"><a href="<?php echo $this->url("tree", 
                array('language'=>$language)) ?>"><?php echo $this->translate('Full tree') ?></a></li>
            <li><a href="<?php echo $this->url("tree/person", 
                array('language'=>$language, 'id'=>94)) ?>"><?php echo $this->translate('Me') ?></a></li>
            <li class="divider"></li>
            <li><a href="<?php echo $this->url("home/default", 
                array('language'=>$language,'controller' => 'About', 'action' => 'technical')) ?>">
                    <?php echo $this->translate('Technical stuff') ?>
                </a>
            </li>
                <li class="divider"></li>
            <li><a href="<?php echo $this->url("home/default", 
                array('language'=>$language,'controller' => 'About', 'action' => 'help')) ?>">
                    <?php echo $this->translate('Help &amp; Support') ?>
                </a>
            </li>
          </ul>
        </li>
      </ul>
        <form class="navbar-form navbar-left" role="search" method="get" action='<?php echo $this->url("tree/search", 
                array('language'=>$language)) ?>'>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="<?php echo $this->translate('Search') ?>">
        </div>
        <button type="submit" class="btn btn-default"><?php echo $this->translate('Submit') ?></button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<?php 
        if ($language == 'ru') {
            $newLanguage = 'en';
            $switch = 'English';
        } else {
            $newLanguage = 'ru';
            $switch = 'Русский';
        }
        
        if (!strpos($this->serverUrl(true), $language)) {
            echo $this->serverUrl(true).$newLanguage;
        } else {
            echo str_ireplace($language, $newLanguage, $this->serverUrl(true));
        }?>">
            <?php echo $switch; ?>
            </a></li>
        <li><a href="<?php echo $this->url("tree/admin", 
                array('language'=>$language)) ?>"><?php echo $this->translate('Log in') ?></a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<?php echo $this->content; ?>

    <hr>
    <footer>
     
    </footer>
    </div>
<?php echo $this->inlineScript() ?>
</body>
</html>
