
<div class="container-fluid">
    <div class="page-header">
        <h1><?php echo $this->translate('Full family tree'); ?></h1>
    </div>
    <?php
//var_dump($this->people);

    ?>
    <div class="tree">
        <ul id="p_root_children" class="root" style="width: 6300px">
            <?php

            $this->nestedList($this->people); ?>
        </ul>
    </div>

    <div class="clearfix"></div>
</div>