
<div class="container">
    <div class="page-header">
        <h1><?php echo $this->translate('Big family project'); ?></h1>
    </div>
    <div class="container-content">
<p>Big family project is a genealogy website for my family, a place dedicated to the memory of great uncle Nil. 
I admit this site isn't getting the time and attention it deserves at the moment but here are my plans for it:
</p>

    <ul>

        <li>Give my family tools to keep our genealogy tree current</li>
        <li>Offer an OAuth-protected API and client libraries so my cousins could integrate this data into their own projects</li>
        <li>Put Nil's book online and build tools for linking people's profiles with the passages from the book</li>
        <li>Offer the site both in English and Russian (though admittedly Google Translate does a great job now!)</li>
        <li>Build some fun data-analysis widgets for calculating family relationships</li>
        <li>Of course an app :)</li>

    </ul>
</div>
</div>
