

<div class="container">
    <div class="page-header">
        <h1><?php echo $this->translate('Nil Shirokov'); ?></h1>
    </div>
    <div class="container-content">
        <p>Great Uncle Nil became a family legend long before he'd hit 30.</p>
        <p>There's a joke in our family that two leading causes of death among us are extreme old age and being killed by Nazis in WW2. 
            Nil ticks both those boxes.</p>
        <p>Due to a clerical error his family had been informed that he'd been killed in battle. They thought him dead for over a month: 
            Unimaginable sorrow, and impossible joy when he'd returned, wounded but alive. 
            He married, had a son and a daughter, four grandchildren, two great-grandchildren born during his lifetime.</p>
        <p>In 1999, at the age of eighty-one, he started his book - probably the first essay he'd written since school. 
            He called it "Big Family" and hand-wrote it in a book-keeper's ledger - no edits, no doubts, barely any misspellings and crossing things out. 
            He drew family tree diagrams by hand. He did all the research single-handedly, mostly by phone, 
            and charted and wrote down everything he knew and remembered about his parents and the rest of his family: 
            his nine siblings, their spouses and all their descendants, several hundreds of them.</p>
        <p>He'd finished it before moving on.</p>

    </div>
</div>
